export const actionTypes = {
    FETCH_ALL_PRODUCTS: 'FETCH_ALL_PRODUCTS',
    SELECTED_SINGLE_PRODUCT: 'SELECTED_SINGLE_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    SELECTED_SINGLE_CATEGORY: 'FETCH_SINGLE_CATEGORY',
    REMOVE_SELECTED_CATEGORY: 'REMOVE_SELECTED_CATEGORY',
    FETCH_PRODUCTS_BY_CATEGORY: 'FETCH_PRODUCTS_BY_CATEGORY',
    REMOVE_SELECTED_CATEGORY_PRODUCTS: 'REMOVE_SELECTED_CATEGORY_PRODUCTS',
    RETRIEVE_CART: 'RETRIEVE_CART',
    UPDATE_CART: 'UPDATE_CART',
    REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
    EMPTY_CART: 'EMPTY_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    REFRESH_CART: 'REFRESH_CART',
    FETCH_SHIPPING_COUNTRIES: 'FETCH_SHIPPING_COUNTRIES',
    GENERATE_CHECKOUT_TOKEN: 'GENERATE_CHECKOUT_TOKEN'
}